name: githubsearch
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  dio: ^5.4.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.4
  flutter_dotenv: ^5.1.0
  flutter_keyboard_visibility: ^6.0.0
  flutter_svg: ^2.0.10+1
  flutter_web_auth: ^0.5.0
  fluttertoast: ^8.2.4
  get_it: ^7.6.7
  go_router: ^13.2.0
  google_fonts: ^6.1.0
  json_annotation: ^4.8.1
  package_info_plus: ^5.0.1
  retrofit: ^4.1.0
  shared_preferences: ^2.2.2
  webview_flutter: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.8
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  retrofit_generator: ^8.1.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/icons/
